version: '3.4'

services:
  flutter: 
    container_name: "flutter"
    hostname: "flutter-base"
    image: "flutter:latest"
    volumes:
      - ../../hoge/:/flutter
    command: /bin/bash -c "/bin/bash"
    environment:
      - FIRESTORE_EMULATOR_HOST=localhost:8080
    tty: true

  firebase:
    container_name: "firebase"
    hostname: "firebase-tools"
    image: "firebase:latest"
    volumes:
      - ../../hoge/firebase/:/firebase
      - ../../hoge/firebase/bin/:/firebase
      - ../../hoge/firebase/config/:/firebase
    ports:
      - 8081:8081 # Emulator Suite UI
      - 5002:5002 # Firebase Hosting
      - 5001:5001 # Clound Functions
      - 9000:9000 # Realtime Database
      - 8080:8080 # Cloud Firestore
      - 8085:8085 # Cloud Pub/Sub
    working_dir: /firebase
    command: /bin/bash -c "/bin/bash"
    tty: true

networks:
  hogehoge:
    external: true
